added feature to also include array as filter in GET /:name/rows route
thevahidal/soul pull request #132
Opened 2023-08-11 14:36 UTC by TahaKhanAbdalli

After this merge the filters in GET `/:name/rows` can also include array e.g. _filters=id:[1,2,3],firstName:John,lastName:Doe

This fix has been sponsored by @IanMayo

2023-08-11 14:40 UTC, IanMayo commented on core/src/controllers/rows.js
> +  const re = /(\w+:?(\[.*?\]|\w+)?)/g;
could you include a comment immediately before you declare `re` to explain that we need to split the filters by `,` except when in an array, please @TahaKhanAbdalli

2023-08-11 15:09 UTC, IanMayo requested changes
Hello @TahaKhanAbdalli - this PR is _slightly_ more difficult to review because your linter is configured to use `"` instead of `'`.
Would you mind changing the config to use `'` string marker, and do a fresh save on this file?
The changes should then be easier to review.

2023-08-11 15:44 UTC, IanMayo approved these changes

2023-08-16 08:46 UTC, IanMayo commented
Hello @thevahidal , any chance of review/merge on this PR please?

It's the last feature required in order for `Soul` to be compliant as a `REST` backend for [`react-admin`](https://marmelab.com/react-admin/)

2023-08-16 17:50 UTC, thevahidal commented
@TahaKhanAbdalli Thanks for the PR, I think it's better if use a syntax like what we have for greater than, less than and ..., in those case we use a `gt`, `lt` lookup appended to the end of the field name, e.g. `id_gt=...`, `id_lt=...`.
I think it's good pattern to also use `in` for multiple lookup values, e.g. `id__in=...`.
@IanMayo What's your opinion on this?

2023-08-16 18:00 UTC, thevahidal commented on core/src/controllers/rows.test.js
> +      '/api/tables/users/rows?_filters=id:2'
It's nice to add a test case for multiple lookups

2023-08-16 18:03 UTC, thevahidal commented
@TahaKhanAbdalli There's also some conflicts needed to be handled.
Would you please bump of the minor version of Soul Core to `v0.6.0`

2023-08-16 18:09 UTC, IanMayo commented
@thevahidal - sure, that strategy separates how API supports single vs multiple key values, which keeps things simple.

2023-08-17 08:04 UTC, IanMayo commented
Hello @TahaKhanAbdalli - I support @thevahidal [suggestion](https://github.com/thevahidal/soul/pull/132#issuecomment-1681040130) to support multiple matching keys using the `__in` operator.

2023-08-17 12:02 UTC, thevahidal commented
@IanMayo, the `__in=` is more of a nice-to-have feature and if `react-admin` is already using it the way @TahaKhanAbdalli implemented it, I'm ok to move on with this.

2023-08-17 12:03 UTC, thevahidal approved these changes
As we discuss it with @IanMayo, moving on with this PR is okay. Thanks, @TahaKhanAbdalli!

2023-08-17 12:03 UTC, merged

2023-08-17 12:06 UTC, thevahidal commented
@all-contributors please add @thevahidal for review.