Auth
thevahidal/soul pull request #164
Opened 2024-03-11 11:18 UTC by AbegaM

### Features 

1. Initial user creation feature
2. APIs for `login`, `signup`, `change password` and `refresh tokens`
3. Feature to update a `superuser` from the `CLI`
4. Authentication and Authorization features

2024-03-12 16:42 UTC, thevahidal requested changes
Thanks @AbegaM,
It was one of the biggest PRs I ever reviewed. I wanna thank you once more for the effort you put into this.
I left some comments and changes, please check them and let me know your thoughts.
Some of the change requests happened in different places, I tried my best to leave comments for all the occurrences of one change request, but I might forget some, so please do the changes everywhere that they apply.

2024-03-12 16:42 UTC, thevahidal commented on src/controllers/rows.test.js
For now, the tests are very good, but I think it's a good idea for the future to instead of superuser use non-superuser roles or write unit tests for auth functions

2024-03-12 16:42 UTC, thevahidal commented on src/controllers/auth.test.js
> +      expect(res.body.message).toBe('Row Inserted');
We can also check that hashed_password / password are not returned.

2024-03-12 16:42 UTC, thevahidal commented on src/controllers/auth.test.js
> +      expect(res.body.data[0]).toHaveProperty('createdAt');
Here also is a good idea to check that sensitive fields are not returned

2024-03-12 16:42 UTC, thevahidal commented on src/controllers/auth.test.js
> +      expect(res.body.message).toBe('Success');
Here we can check tokens inside response cookie

2024-03-12 16:42 UTC, thevahidal commented on src/controllers/auth.test.js
> +          `accessToken=${accessToken}`,
Refresh endpoint should not need access token

2024-03-12 16:42 UTC, thevahidal commented on src/controllers/auth.test.js
> +      expect(res.body.message).toBe('Password updated successfully');
Here we can check that if password is really updated

2024-03-12 16:48 UTC, thevahidal commented
@AbegaM, we also need to protect the transactions endpoint to only be accessible by superuser

2024-03-12 16:57 UTC, IanMayo commented on src/controllers/auth.js
> +          is_superuser: 'false',
We did debate this.  It seemed like we were relaxing security more than we needed to.  If we have correctly configured user roles/permissions we would be able to use the app without needing a superuser.  It is still possible to convert the initial user to superuser via the CLI - so it only takes a few seconds, if it's necessary.

But note: in my context we won't have initial user, our users table will already be populated.

2024-03-13 10:28 UTC, AbegaM commented on src/constants/api.js
> +  defaultRoutes: ['_users', '_roles', '_roles_permissions', '_users_roles'],
Hello @thevahidal , I have made this duplicate intentionally, I am trying to differentiate `API layer` related fields and `DB layer` related fields, the above constants represent the `API` endpoints and we might decide to change them in the future, so we will do the modification here, the once in the `tables.js` file are fields related with `Database` table names. If you think it is better to not duplicate them i can use one `constant` for all API and Db data

2024-03-14 14:28 UTC, thevahidal commented on src/constants/api.js
> +  defaultRoutes: ['_users', '_roles', '_roles_permissions', '_users_roles'],
Yeah, I see your point, let's keep it the way it is.

2024-03-15 07:25 UTC, AbegaM commented on src/controllers/auth.js
> +    }
This is a custom route `/api/tables/<table_name>/rows` so i don't think we can modify the schema for it since this route can be used for any resource

2024-03-18 12:23 UTC, AbegaM commented on src/controllers/auth.js
> +        console.log('Your password should be at least 8 charachters long');
No, The problem is the `console.log` message and it is fixed now and it is coming from the `constants` folder

2024-03-18 20:42 UTC, thevahidal approved these changes

2024-03-18 20:43 UTC, merged