Fix cors origin error in the CLI
thevahidal/soul pull request #85
Opened 2023-06-20 16:59 UTC by AbegaM

## Modifications 

1. Added a validation to check if `argv.cors` is falsy in the `config/index.js` file:
    ```js
       cors: {
           origin: argv.cors?.split(',') ||
           envVars.CORS_ORIGIN_WHITELIST?.split(',') || ['*'],
        },
     ```

2. Modified the code in `src/index.js` to fix the issue with CORS not allowing access from all origins when the user passes `*` from the CLI:
     ```js
       const corsOrigin = config.cors.origin
       const corsOptions = {
           origin: corsOrigin[0] === '*' ? '*' : corsOrigin
        };
       app.use(cors(corsOptions))
      ```

2023-06-25 17:49 UTC, AbegaM commented
Hello @thevahidal,

Could you please review this PR at your earliest convenience? When I submitted the last PR, there were some errors that prevented the CORS from allowing all origins when passing * to the -c flag. However, I have since fixed and tested everything. I would greatly appreciate it if you could review the changes I have made.

Thank you.

2023-06-29 19:56 UTC, thevahidal commented
Hey @AbegaM, Sorry for the late response, I'll merge it asap.

2023-06-29 20:01 UTC, thevahidal requested changes
Thanks for your PR, please also make sure to increase the minor version.

2023-06-29 20:01 UTC, thevahidal commented on README.md
> +Run `soul -d sqlite.db -p 8000 -c "*"` and it'll start a REST API on [http://localhost:8000](http://localhost:8000) and a Websocket server on [ws://localhost:8000](ws://localhost:8000).
You provided `*` as the default cors option so I think it's better not to include it here

2023-06-29 20:01 UTC, thevahidal requested changes
Thanks for your PR, please also make sure to increase the minor version.

2023-06-30 15:34 UTC, AbegaM commented
Hi @thevahidal 

I have fixed the issues, please review my changes when you have time and let me know if there is anything that needs to be modified.

2023-06-30 15:43 UTC, AbegaM commented
Hi @thevahidal

I have pushed two commits and have fixed the issues, please review my changes when you have time and let me know if there is anything that needs to be modified.

2023-06-30 15:52 UTC, thevahidal approved these changes

2023-06-30 15:52 UTC, merged

2023-06-30 16:08 UTC, AbegaM commented
@thevahidal, please let me know when you publish the changes to npm